{
 "title": "Domain - Interface",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "query": {
     "query": "label_values(nginx_http_response_count_total, host)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(nginx_http_response_count_total{host=\"$domain\"}, request_uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_count{host=\"$domain\", request_uri=~\"$interface\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{host=\"$domain\",request_uri=~\"$interface\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_time_seconds_sum{host=\"$domain\", request_uri=~\"$interface\"}[5m])) by (instance) / sum(rate(nginx_http_response_time_seconds_count{host=\"$domain\", request_uri=~\"$interface\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Response time (90% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nginx_http_response_time_seconds{quantile=\"0.9\",method=\"GET\",status=\"200\",host=\"$domain\",request_uri=~\"$interface\"}"
    }
   ]
  },
  {
   "title": "HTTP traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{host=\"$domain\",request_uri=~\"$interface\"}[5m])) by (instance) /1024 /1024"
    }
   ]
  }
 ]
}